#!/usr/bin/env bash
# =============================================================================
# AIWorker VPS Setup Script
# Target: 32GB RAM, CPU-only, Ubuntu 22.04/24.04, NVMe storage
# Run as root: sudo bash setup_vps.sh
# =============================================================================
set -euo pipefail

AIWORKER_USER="${AIWORKER_USER:-aiworker}"
AIWORKER_DIR="${AIWORKER_DIR:-/opt/aiworker}"
SWAP_SIZE_GB="${SWAP_SIZE_GB:-50}"
SWAP_FILE="${SWAP_FILE:-/swapfile}"
OLLAMA_MODEL="${OLLAMA_MODEL:-deepseek-coder:6.7b}"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

# ── 1. System packages ────────────────────────────────────────────────
log "Installing system packages..."
apt-get update -qq
apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv \
    git curl wget \
    patch \
    sqlite3 \
    docker.io \
    semgrep \
    htop \
    2>&1 | tail -5

# ── 2. Swap space (50GB NVMe swap) ────────────────────────────────────
log "Configuring ${SWAP_SIZE_GB}GB swap..."
if swapon --show | grep -q "$SWAP_FILE"; then
    log "Swap already active at $SWAP_FILE"
else
    fallocate -l "${SWAP_SIZE_GB}G" "$SWAP_FILE" || dd if=/dev/zero of="$SWAP_FILE" bs=1G count="$SWAP_SIZE_GB"
    chmod 600 "$SWAP_FILE"
    mkswap "$SWAP_FILE"
    swapon "$SWAP_FILE"
    echo "$SWAP_FILE none swap sw 0 0" >> /etc/fstab
    log "Swap enabled: $(swapon --show)"
fi

# ── 3. Kernel tuning for AI workloads ────────────────────────────────
log "Applying kernel tuning..."
cat >> /etc/sysctl.conf << 'EOF'
# AIWorker VPS optimisations
vm.swappiness=80
vm.vfs_cache_pressure=50
vm.dirty_ratio=15
vm.dirty_background_ratio=5
EOF
sysctl -p /etc/sysctl.conf

# ── 4. Ollama installation ────────────────────────────────────────────
log "Installing Ollama..."
if ! command -v ollama &>/dev/null; then
    curl -fsSL https://ollama.com/install.sh | sh
fi

# Configure Ollama for single-model sequential use
mkdir -p /etc/ollama
cat > /etc/ollama/ollama.env << 'EOF'
OLLAMA_NUM_PARALLEL=1
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_KEEP_ALIVE=5m
OLLAMA_HOST=127.0.0.1:11434
EOF

# Create systemd service for Ollama with RAM-safe settings
cat > /etc/systemd/system/ollama.service << 'EOF'
[Unit]
Description=Ollama Local LLM Server
After=network.target

[Service]
Type=simple
User=ollama
EnvironmentFile=/etc/ollama/ollama.env
ExecStart=/usr/local/bin/ollama serve
Restart=on-failure
RestartSec=10
LimitNOFILE=65536
# Kill Ollama if it exceeds 20GB RAM (leaves 12GB for system + Python)
MemoryMax=20G
MemorySwapMax=30G

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable ollama
systemctl start ollama
log "Waiting for Ollama to start..."
sleep 5

# ── 5. Pull LLM model ────────────────────────────────────────────────
log "Pulling model: $OLLAMA_MODEL (this may take several minutes)..."
ollama pull "$OLLAMA_MODEL"

# ── 6. SearXNG (local search engine) ─────────────────────────────────
log "Starting SearXNG..."
systemctl start docker || true
docker pull searxng/searxng 2>&1 | tail -3

# Check if container already exists
if docker ps -a --format '{{.Names}}' | grep -q '^aiworker-searxng$'; then
    docker start aiworker-searxng || true
else
    docker run -d \
        --name aiworker-searxng \
        --restart unless-stopped \
        -p 127.0.0.1:8888:8080 \
        -e "SEARXNG_BASE_URL=http://localhost:8888" \
        searxng/searxng
fi
log "SearXNG running at http://localhost:8888"

# ── 7. AIWorker Python environment ───────────────────────────────────
log "Setting up Python environment..."
if ! id "$AIWORKER_USER" &>/dev/null; then
    useradd -r -m -d "$AIWORKER_DIR" -s /bin/bash "$AIWORKER_USER"
fi

mkdir -p "$AIWORKER_DIR"
chown "$AIWORKER_USER:$AIWORKER_USER" "$AIWORKER_DIR"

sudo -u "$AIWORKER_USER" bash << PYSETUP
cd "$AIWORKER_DIR"
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip wheel -q
pip install \
    httpx>=0.27 \
    beautifulsoup4>=4.12 \
    lxml>=5.2 \
    fastapi>=0.110 \
    uvicorn>=0.29 \
    pydantic>=2.0 \
    psutil>=5.9 \
    requests>=2.31 \
    -q
echo "Python environment ready."
PYSETUP

# ── 8. AIWorker environment file ─────────────────────────────────────
log "Writing environment configuration..."
cat > "$AIWORKER_DIR/.env" << EOF
# AIWorker VPS configuration
# Generated by setup_vps.sh — edit as needed

AIWORKER_MODEL=deepseek-coder:6.7b
AIWORKER_DB_PATH=$AIWORKER_DIR/data/aiworker.db
AIWORKER_WORKSPACE=$AIWORKER_DIR/workspace
AIWORKER_SEARXNG_URL=http://localhost:8888
AIWORKER_LLM_ENDPOINT=http://localhost:11434/api/generate

# Safety: NEVER set AIWORKER_AUTO_APPROVE=true on VPS
AIWORKER_AUTO_APPROVE=false

# Governance
AIWORKER_MAX_ATTEMPTS=4
AIWORKER_MAX_FAILURES=3
AIWORKER_SANDBOX_TIMEOUT=120
AIWORKER_RESEARCH_SOURCES=5
AIWORKER_RAM_BUDGET_GB=28.0

# Dashboard
AIWORKER_ADMIN_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
AIWORKER_DASHBOARD_HOST=127.0.0.1
AIWORKER_DASHBOARD_PORT=8000

# Ollama
OLLAMA_NUM_PARALLEL=1
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_KEEP_ALIVE=5m
EOF

mkdir -p "$AIWORKER_DIR/data" "$AIWORKER_DIR/workspace"
chown -R "$AIWORKER_USER:$AIWORKER_USER" "$AIWORKER_DIR"

# ── 9. Systemd service for AIWorker dashboard ────────────────────────
cat > /etc/systemd/system/aiworker-dashboard.service << EOF
[Unit]
Description=AIWorker Monitoring Dashboard
After=network.target ollama.service

[Service]
Type=simple
User=$AIWORKER_USER
WorkingDirectory=$AIWORKER_DIR
EnvironmentFile=$AIWORKER_DIR/.env
ExecStart=$AIWORKER_DIR/venv/bin/uvicorn aiworker.dashboard.server:app \\
    --host \${AIWORKER_DASHBOARD_HOST} \\
    --port \${AIWORKER_DASHBOARD_PORT} \\
    --workers 1
Restart=on-failure
RestartSec=10
MemoryMax=512M

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable aiworker-dashboard

# ── 10. Cron schedule (3-4 cycles/day) ───────────────────────────────
log "Installing cron schedule..."
crontab -u "$AIWORKER_USER" - << CRONEOF
# AIWorker autonomous cycles — 4 runs per day, 6 hours apart
# Adjust goals as needed
0 6  * * * cd $AIWORKER_DIR && source venv/bin/activate && python main.py run "improve test coverage" >> logs/cycle.log 2>&1
0 12 * * * cd $AIWORKER_DIR && source venv/bin/activate && python main.py run "add input validation" >> logs/cycle.log 2>&1
0 18 * * * cd $AIWORKER_DIR && source venv/bin/activate && python main.py run "refactor for readability" >> logs/cycle.log 2>&1
0 0  * * * cd $AIWORKER_DIR && source venv/bin/activate && python main.py self-improve >> logs/cycle.log 2>&1
CRONEOF

mkdir -p "$AIWORKER_DIR/logs"
chown "$AIWORKER_USER:$AIWORKER_USER" "$AIWORKER_DIR/logs"

# ── 11. Summary ───────────────────────────────────────────────────────
log ""
log "======================================================================"
log "  AIWorker VPS Setup Complete"
log "======================================================================"
log ""
log "  Ollama:     http://localhost:11434  (model: $OLLAMA_MODEL)"
log "  SearXNG:    http://localhost:8888"
log "  Dashboard:  http://localhost:8000   (after: pip install -e .)"
log ""
log "  Admin token: $(grep AIWORKER_ADMIN_TOKEN $AIWORKER_DIR/.env | cut -d= -f2)"
log ""
log "  Next steps:"
log "    1. cd $AIWORKER_DIR && git clone <repo> ."
log "    2. source venv/bin/activate && pip install -e ."
log "    3. python main.py status"
log "    4. systemctl start aiworker-dashboard"
log ""
log "  RAM budget check:"
free -h | grep -E "Mem|Swap"
log "======================================================================"
