#!/usr/bin/env python3
"""
AIWorker 2.0 — The Seed
Single-file bootstrap for autonomous self-improving agent.
https://ark.aiworker/seed/v2.0.0

Usage:
    python seed.py bootstrap          # Build full AIWorker from seed
    python seed.py verify             # Check system integrity
    python seed.py self-improve       # Begin autonomous improvement
    python seed.py status             # Show current state

Constraints:
    - Maximum 1000 lines
    - Python 3.8+ standard library ONLY
    - No external dependencies
    - Self-contained and self-modifying
"""

# ============ IMPORTS (stdlib only) ============
import ast
import base64
import hashlib
import json
import os
import re
import subprocess
import sys
import time
import urllib.request
import zlib
from pathlib import Path
from typing import Optional, Tuple, Dict, List, Any

# ============ CONSTANTS ============
VERSION = "2.0.0-seed"
MAX_LINES = 1000
ARK_URL = os.getenv("AIWORKER_ARK", "https://ark.aiworker")
OLLAMA_MODEL = os.getenv("AIWORKER_MODEL", "tinyllama")
FORBIDDEN_PATTERNS = [
    'eval(', 'exec(', '__import__(', 'os.system(', 'subprocess.call',
    'subprocess.run', 'shell=True', 'compile(', 'input()'
]
SAFETY_PAUSE = 5
MAX_GENERATIONS_PER_MINUTE = 1

# ============ EMBEDDED BLUEPRINT ============
# Compressed manifest of full system (placeholder - real one generated by packager)
BLUEPRINT = b"eJyrVspIzcnJV7JSqlSyUtJRKkktLlGyUoCBPAVbhbzUFAVbhTRbhbz8fAVbhTRbBX0QAwJoQzQhGgD5+SlW+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62goF+UWp8SWJOSlKOkowM0DCtja2CgWJRanJ2cU62go="

# ============ STATE ============
_generation_times: List[float] = []

# ============ LLM INTERFACE ============
def llm(prompt: str, model: str = OLLAMA_MODEL, timeout: int = 60) -> str:
    """Call local LLM via ollama subprocess."""
    try:
        cmd = ["ollama", "run", model, prompt]
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return f"# Error: {result.stderr}"
    except FileNotFoundError:
        return "# Error: ollama not found. Install from ollama.ai"
    except subprocess.TimeoutExpired:
        return "# Error: LLM call timed out"
    except Exception as e:
        return f"# Error: {e}"

# ============ SAFETY ============
def validate_code(code: str) -> Tuple[bool, str]:
    """AST parse and forbidden pattern check."""
    # Check forbidden patterns
    for pattern in FORBIDDEN_PATTERNS:
        if pattern in code:
            return False, f"Forbidden pattern: {pattern}"
    
    # AST validation
    try:
        tree = ast.parse(code)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                # Check for dangerous calls
                if isinstance(node.func, ast.Name):
                    if node.func.id in ['eval', 'exec', 'compile', '__import__']:
                        return False, f"Forbidden function: {node.func.id}"
                # Check for subprocess with shell
                if isinstance(node.func, ast.Attribute):
                    if node.func.attr in ['system', 'popen']:
                        return False, f"Forbidden: {node.func.attr}"
        return True, "Valid"
    except SyntaxError as e:
        return False, f"Syntax error: {e}"

def human_confirm(action: str, detail: str) -> bool:
    """Prompt for confirmation in TTY, auto-deny elsewhere."""
    if not sys.stdin.isatty():
        print(f"[NON-TTY] Would ask: {action}")
        print(f"Detail: {detail}")
        return False
    
    print(f"\n{'='*50}")
    print(f"ACTION: {action}")
    print(f"{'='*50}")
    print(detail)
    print(f"{'='*50}")
    print(f"Waiting {SAFETY_PAUSE} seconds...")
    time.sleep(SAFETY_PAUSE)
    
    response = input("Approve? (yes/no): ").strip().lower()
    return response == 'yes'

def rate_limit_check() -> bool:
    """Enforce generation rate limit."""
    now = time.time()
    global _generation_times
    _generation_times = [t for t in _generation_times if now - t < 60]
    if len(_generation_times) >= MAX_GENERATIONS_PER_MINUTE:
        return False
    _generation_times.append(now)
    return True

# ============ CODE GENERATION ============
def generate_module(name: str, spec: str, examples: List[str] = None) -> str:
    """Generate Python module using LLM."""
    if not rate_limit_check():
        return "# Rate limit exceeded. Wait 60 seconds."
    
    prompt = f"""Generate a complete Python module named '{name}'.

Specification:
{spec}

Requirements:
- Use only Python standard library
- Include proper docstrings
- No external dependencies
- Safe code (no eval, exec, os.system)
- Follow PEP 8 style

Examples:
{chr(10).join(examples or [])}

Output only the Python code, no explanations."""

    return llm(prompt)

def generate_config_module() -> str:
    """Generate the config module."""
    spec = """Configuration module for AIWorker.
    - Load/save config from JSON file
    - Environment variable overrides
    - Default values for 32GB VPS
    - Safety settings (auto_approve=False)"""
    
    return '''"""AIWorker configuration module."""
import json
import os
from pathlib import Path
from typing import Dict, Any, Optional

DEFAULT_CONFIG = {
    "version": "2.0.0",
    "auto_approve": False,
    "ollama_model": "tinyllama",
    "max_memory_gb": 20,
    "checkpoint_interval": 300,
    "log_level": "INFO",
    "enable_mesh": True,
    "enable_self_modify": True,
    "safety_cage_enabled": True,
    "max_iterations_per_day": 10,
    "backup_enabled": True,
}

class Config:
    """Configuration manager."""
    
    def __init__(self, config_path: Optional[Path] = None):
        self.config_path = config_path or Path("aiworker.json")
        self._config = self._load()
    
    def _load(self) -> Dict[str, Any]:
        """Load config from file or create default."""
        if self.config_path.exists():
            with open(self.config_path) as f:
                return {**DEFAULT_CONFIG, **json.load(f)}
        return DEFAULT_CONFIG.copy()
    
    def save(self) -> None:
        """Save config to file."""
        with open(self.config_path, 'w') as f:
            json.dump(self._config, f, indent=2)
    
    def get(self, key: str, default: Any = None) -> Any:
        """Get config value with env override."""
        env_key = f"AIWORKER_{key.upper()}"
        if env_key in os.environ:
            return os.environ[env_key]
        return self._config.get(key, default)
    
    def set(self, key: str, value: Any) -> None:
        """Set config value."""
        self._config[key] = value
        self.save()
    
    @property
    def auto_approve(self) -> bool:
        """Safety: Never auto-approve changes."""
        return False  # Hardcoded safety
    
    def __getitem__(self, key: str) -> Any:
        return self.get(key)

# Global config instance
config = Config()
'''

def generate_safety_module() -> str:
    """Generate the safety cage module."""
    spec = """Safety cage with three-tier validation:
    - AST analysis for forbidden patterns
    - Human approval for modifications
    - Kill switch for emergency stop"""
    
    return '''"""Safety cage for AIWorker."""
import ast
import os
import sys
from pathlib import Path
from typing import Tuple, List, Optional

FORBIDDEN_PATTERNS = [
    'eval(', 'exec(', '__import__(', 'os.system(',
    'subprocess.call', 'shell=True', 'compile(',
]

FORBIDDEN_NAMES = {'eval', 'exec', 'compile', '__import__'}

class SafetyCage:
    """Three-tier safety validation."""
    
    def __init__(self):
        self.kill_switch_path = Path(".aiworker_kill")
        self.approval_log: List[dict] = []
    
    def check_kill_switch(self) -> bool:
        """Check if kill switch is active."""
        return self.kill_switch_path.exists()
    
    def trigger_kill_switch(self, reason: str) -> None:
        """Activate kill switch."""
        self.kill_switch_path.write_text(f"Killed: {reason}\\n")
        print(f"KILL SWITCH ACTIVATED: {reason}")
        sys.exit(1)
    
    def ast_validate(self, code: str) -> Tuple[bool, str]:
        """Tier 1: AST validation."""
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if node.func.id in FORBIDDEN_NAMES:
                        return False, f"Forbidden: {node.func.id}()"
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name in {'subprocess', 'os'}:
                        pass  # Allowed but monitored
        return True, "AST validation passed"
    
    def pattern_validate(self, code: str) -> Tuple[bool, str]:
        """Tier 2: Pattern matching."""
        for pattern in FORBIDDEN_PATTERNS:
            if pattern in code:
                return False, f"Forbidden pattern: {pattern}"
        return True, "Pattern validation passed"
    
    def human_approve(self, action: str, detail: str) -> bool:
        """Tier 3: Human approval."""
        if self.check_kill_switch():
            print("Kill switch active - rejecting")
            return False
        
        if not sys.stdin.isatty():
            print(f"[NON-TTY] Approval required: {action}")
            return False
        
        print(f"\\n{'='*50}")
        print(f"APPROVAL REQUIRED: {action}")
        print(f"{'='*50}")
        print(detail[:2000] + "..." if len(detail) > 2000 else detail)
        print(f"{'='*50}")
        
        response = input("Approve? (yes/no): ").strip().lower()
        approved = response == 'yes'
        
        self.approval_log.append({
            'action': action,
            'approved': approved,
            'timestamp': __import__('time').time()
        })
        return approved
    
    def validate(self, code: str, action: str) -> Tuple[bool, str]:
        """Full three-tier validation."""
        if self.check_kill_switch():
            return False, "Kill switch active"
        
        # Tier 1: AST
        ok, msg = self.ast_validate(code)
        if not ok:
            return False, msg
        
        # Tier 2: Pattern
        ok, msg = self.pattern_validate(code)
        if not ok:
            return False, msg
        
        # Tier 3: Human approval for modifications
        if 'modify' in action.lower() or 'write' in action.lower():
            if not self.human_approve(action, code[:500]):
                return False, "Human approval denied"
        
        return True, "All validations passed"

# Global safety cage instance
safety_cage = SafetyCage()
'''

# ============ SELF-MODIFICATION ============
def write_module(name: str, code: str) -> Path:
    """Write module to aiworker/ directory."""
    base_dir = Path("aiworker")
    parts = name.split('.')
    
    if len(parts) > 1:
        module_dir = base_dir / parts[0]
        module_dir.mkdir(parents=True, exist_ok=True)
        file_path = module_dir / f"{parts[1]}.py"
    else:
        file_path = base_dir / f"{name}.py"
    
    base_dir.mkdir(exist_ok=True)
    
    with open(file_path, 'w') as f:
        f.write(code)
    
    # Create __init__.py if needed
    init_file = file_path.parent / "__init__.py"
    if not init_file.exists():
        init_file.write_text('"""AIWorker module."""\n')
    
    return file_path

def backup_seed() -> Path:
    """Create backup of seed.py before modification."""
    seed_path = Path(__file__)
    backup_path = seed_path.with_suffix('.py.backup')
    backup_path.write_text(seed_path.read_text())
    return backup_path

def integrate_self(code: str) -> bool:
    """Add capability to seed itself (careful)."""
    valid, reason = validate_code(code)
    if not valid:
        print(f"Validation failed: {reason}")
        return False
    
    if not human_confirm("Self-modification", code[:1000]):
        print("Self-modification denied")
        return False
    
    backup = backup_seed()
    print(f"Backup created: {backup}")
    
    seed_path = Path(__file__)
    with open(seed_path, 'a') as f:
        f.write(f"\n# Self-modification: {time.time()}\n")
        f.write(code)
    
    print("Self-modification applied")
    return True

# ============ DOWNLOAD ============
def fetch_module(name: str) -> Optional[str]:
    """Download module from Ark."""
    url = f"{ARK_URL}/modules/{name}.py"
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            code = response.read().decode('utf-8')
            valid, reason = validate_code(code)
            if valid:
                return code
            print(f"Downloaded code invalid: {reason}")
            return None
    except urllib.error.URLError as e:
        print(f"Download failed: {e}")
        return None
    except Exception as e:
        print(f"Download error: {e}")
        return None

def verify_hash(code: str, expected_hash: str) -> bool:
    """Verify code hash matches expected."""
    actual = hashlib.sha256(code.encode()).hexdigest()[:16]
    return actual == expected_hash

# ============ BOOTSTRAP ============
def get_blueprint() -> Dict[str, Any]:
    """Decompress and parse embedded blueprint."""
    try:
        decoded = base64.b64decode(BLUEPRINT)
        decompressed = zlib.decompress(decoded)
        return json.loads(decompressed)
    except Exception:
        # Return minimal blueprint for bootstrap
        return {
            "phases": {
                "1": ["config", "safety_cage", "engine"],
                "2": ["mcp", "self_modify"],
                "3": ["telemetry", "health"],
            },
            "modules": {
                "config": {"hash": "placeholder", "deps": []},
                "safety_cage": {"hash": "placeholder", "deps": ["config"]},
                "engine": {"hash": "placeholder", "deps": ["config", "safety_cage"]},
            }
        }

def check_environment() -> Tuple[bool, str]:
    """Verify environment can run AIWorker."""
    # Check Python version
    if sys.version_info < (3, 8):
        return False, f"Python 3.8+ required, got {sys.version_info}"
    
    # Check disk space (rough estimate)
    try:
        stat = os.statvfs('.')
        free_mb = (stat.f_bavail * stat.f_frsize) / (1024 * 1024)
        if free_mb < 1000:
            return False, f"Insufficient disk: {free_mb:.0f}MB free"
    except Exception:
        pass
    
    # Check ollama
    try:
        subprocess.run(['ollama', '--version'], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        print("Warning: ollama not found. Install from ollama.ai")
    
    return True, "Environment OK"

def bootstrap_phase(phase_num: int, modules: List[str]) -> bool:
    """Bootstrap one phase of AIWorker."""
    print(f"\n{'='*50}")
    print(f"BOOTSTRAPPING PHASE {phase_num}")
    print(f"{'='*50}")
    
    for module_name in modules:
        print(f"\nGenerating module: {module_name}")
        
        # Try to fetch from Ark first
        code = fetch_module(module_name)
        
        # Fallback to local generation
        if code is None:
            print(f"Fetching failed, generating locally...")
            if module_name == 'config':
                code = generate_config_module()
            elif module_name == 'safety_cage':
                code = generate_safety_module()
            else:
                spec = f"Module {module_name} for AIWorker"
                code = generate_module(module_name, spec)
        
        # Validate
        valid, reason = validate_code(code)
        if not valid:
            print(f"Validation failed: {reason}")
            continue
        
        # Write module
        path = write_module(module_name, code)
        print(f"Written: {path}")
        
        # Verify import
        try:
            __import__(f"aiworker.{module_name}")
            print(f"Import verified: aiworker.{module_name}")
        except ImportError as e:
            print(f"Import failed: {e}")
    
    return True

def verify_system() -> Dict[str, Any]:
    """Verify reconstructed system."""
    blueprint = get_blueprint()
    results = {
        "modules_checked": 0,
        "modules_valid": 0,
        "modules_missing": [],
        "modules_modified": []
    }
    
    base_dir = Path("aiworker")
    for name, info in blueprint.get("modules", {}).items():
        results["modules_checked"] += 1
        module_path = base_dir / f"{name}.py"
        
        if not module_path.exists():
            results["modules_missing"].append(name)
            continue
        
        code = module_path.read_text()
        expected_hash = info.get("hash", "")
        
        if expected_hash != "placeholder":
            if verify_hash(code, expected_hash):
                results["modules_valid"] += 1
            else:
                results["modules_modified"].append(name)
        else:
            results["modules_valid"] += 1
    
    return results

# ============ MAIN ============
def print_status():
    """Print current system status."""
    print(f"\n{'='*50}")
    print(f"AIWorker Seed v{VERSION}")
    print(f"{'='*50}")
    
    env_ok, env_msg = check_environment()
    print(f"Environment: {env_msg}")
    
    blueprint = get_blueprint()
    print(f"Blueprint: {len(blueprint.get('modules', {}))} modules defined")
    
    base_dir = Path("aiworker")
    if base_dir.exists():
        modules = list(base_dir.glob("*.py")) + list(base_dir.glob("*/*.py"))
        modules = [m for m in modules if m.name != "__init__.py"]
        print(f"Installed: {len(modules)} modules")
    else:
        print("Installed: None (run 'bootstrap' first)")
    
    kill_switch = Path(".aiworker_kill")
    print(f"Kill switch: {'ACTIVE' if kill_switch.exists() else 'inactive'}")
    print(f"{'='*50}\n")

def main():
    """Entry point."""
    args = sys.argv[1:] if len(sys.argv) > 1 else ['status']
    command = args[0]
    
    if command == 'bootstrap':
        env_ok, env_msg = check_environment()
        if not env_ok:
            print(f"Environment check failed: {env_msg}")
            sys.exit(1)
        
        print("Starting AIWorker bootstrap...")
        
        # Phase 1: Foundation
        bootstrap_phase(1, ['config', 'safety_cage', 'engine'])
        
        # Phase 2: Integration
        bootstrap_phase(2, ['mcp', 'self_modify', 'state_handlers'])
        
        # Phase 3: Production
        bootstrap_phase(3, ['telemetry', 'health', 'backup'])
        
        print("\n" + "="*50)
        print("Bootstrap complete!")
        print("Run 'python seed.py verify' to check system")
        print("Run 'python seed.py self-improve' to begin")
        print("="*50)
    
    elif command == 'verify':
        results = verify_system()
        print(f"\nVerification Results:")
        print(f"  Modules checked: {results['modules_checked']}")
        print(f"  Modules valid: {results['modules_valid']}")
        if results['modules_missing']:
            print(f"  Missing: {', '.join(results['modules_missing'])}")
        if results['modules_modified']:
            print(f"  Modified: {', '.join(results['modules_modified'])}")
    
    elif command == 'self-improve':
        print("Starting self-improvement loop...")
        print("(This would delegate to aiworker.main in full system)")
        
        # Check if full system exists
        main_path = Path("aiworker/main.py")
        if main_path.exists():
            print("Handing off to full AIWorker system...")
            os.execvp(sys.executable, [sys.executable, "-m", "aiworker.main", "self-improve"])
        else:
            print("Full system not found. Run 'bootstrap' first.")
    
    elif command == 'status':
        print_status()
    
    elif command == 'help':
        print(__doc__)
    
    else:
        print(f"Unknown command: {command}")
        print("Use: bootstrap, verify, self-improve, status, help")
        sys.exit(1)

if __name__ == "__main__":
    main()

